# To implement Python string functions
print (" ALPHA TESTING FOR STRING FUNCTIONS ")
print (" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ")
a = str(input("Enter Some Gibberish : "))
b = input("Enter the spacing :")
print("The string entered is a word : ",a.isalpha())
print("The string entered in lowercase : ",a.lower())
print("The string entered is in lowercase : ",a.islower())
print("The string entered in uppercase : ",a.upper())
print("The string entered is in uppercase : ",a.isupper())
print("The string entered after removing the space from left side : ",a.lstrip())
print("The string entered after removing the space from right side : ",a.rstrip())
print("The string entered contains whitespace : ",a.isspace())
print("The string entered is titlecased : ",a.istitle())
print("The string entered after joining with ",b," : ",b.join(a))
print("The string entered after swaping case : ",a.swapcase())